# **Numpy**

In [9]:
import numpy as np
type(np.random)

module

In [10]:
rolls = np.random.randint(low=1, high=6, size=10)
print(rolls)
print(type(rolls))  


[4 4 4 3 3 1 2 3 5 2]
<class 'numpy.ndarray'>


np.random.randint: 균등 분포 정수 난수 1개 생성  

## **ndarray**
Numpy의 핵심인 다차원 행렬 자료구조 클래스
선언은 a = np.array([])의 형태    
출력형태는 List와 같음  

### **Python list**
* 여러가지 타입의 원소 
* Linked list 구현  
* 메모리 용량이 크고 속도가 느림  
* 벡터화 연산 불가  

### **Numpy ndarray**  
* 동일 타입의 원소  
* contiguous memory layout (연속 메모리 할당) : C계열 메모리
* 메모리 최적화, 계산 속도 향상  
* 벡터화 연산 가능  

In [11]:
# [1,2,3] + 10 이라는 연산은 말도 안된다 but 벡터화 연산에서는 ?
print(rolls)
print(rolls+10)

[4 4 4 3 3 1 2 3 5 2]
[14 14 14 13 13 11 12 13 15 12]


In [12]:
xlist = [[1,2,3],[4,5,6]]
print(xlist)
copyxList = np.asarray(xlist)
copyxList

[[1, 2, 3], [4, 5, 6]]


array([[1, 2, 3],
       [4, 5, 6]])

np.asarray()와 np.array()는 기능에 있어서 차이는 없지만 복사 관련하여 차이가 있음  
(정확히는 모르겠음..)

In [13]:
#ndarray 출력하기
print(copyxList[0,2]) 
print(copyxList[0])

3
[1 2 3]


## Tensorflow 

In [14]:
import tensorflow as tf
a = tf.constant(1)
b = tf.constant(1)
a + b



<tf.Tensor: shape=(), dtype=int32, numpy=2>

# **문제 풀기**    

### **문제**  
연산자 오퍼레이팅 문제 : 아래함수 채우기

In [ ]:
def blackjack_hand_greater_than(hand_1, hand_2):
    """
    Return True if hand_1 beats hand_2, and False otherwise.
    
    In order for hand_1 to beat hand_2 the following must be true:
    - The total of hand_1 must not exceed 21
    - The total of hand_1 must exceed the total of hand_2 OR hand_2's total must exceed 21
    
    Hands are represented as a list of cards. Each card is represented by a string.
    
    When adding up a hand's total, cards with numbers count for that many points. Face
    cards ('J', 'Q', and 'K') are worth 10 points. 'A' can count for 1 or 11.
    
    When determining a hand's total, you should try to count aces in the way that 
    maximizes the hand's total without going over 21. e.g. the total of ['A', 'A', '9'] is 21,
    the total of ['A', 'A', '9', '3'] is 14.
    
    Examples:
    >>> blackjack_hand_greater_than(['K'], ['3', '4'])
    True
    >>> blackjack_hand_greater_than(['K'], ['10'])
    False
    >>> blackjack_hand_greater_than(['K', 'K', '2'], ['3'])
    False
    """
    pass


### **답**

In [38]:
def blackjack_hand_greater_than(hand_1, hand_2):

    count1 = 0
    total1 = 0

    for list1 in hand_1:
        if(list1 == 'A'):
            count1 = count1 + 1
        elif(list1 == 'K' or list1 == 'Q' or list1 == 'J'):
            total1 = total1 + 10
        else:
            total1 = total1 + int(list1)

    total1 = total1 + count1

    if(total1 > 21):
        return False

    for i in range(count1):
        if(total1 + 10 > 21):
            break
        else:
            total1 = total1 + 10
            
    count2 = 0
    total2 = 0
    for list2 in hand_2:
        if(list2 == 'A'):
            count2 = count2 + 1
        elif(list2 == 'K' or list2 == 'Q' or list2 == 'J'):
            total2 = total2 + 10
        else:
            total2 = total2 + int(list2)
            
    total2 = total2 + count2
    if(total2 > 21):
        return True
    
    for i in range(count2):
        if(total2 + 10 > 21):
            break
        else:
            total2 = total2 + 10
            

    if(total1 > total2):
        return True
    else:
        return False


print(blackjack_hand_greater_than(['K'], ['3', '4']))
print(blackjack_hand_greater_than(['K'], ['10']))
print(blackjack_hand_greater_than(['K', 'K', '2'], ['3']))
blackjack_hand_greater_than(['3', '2', '6', '8'], ['8', 'A', '5'])



7
True
10
False
False
24


False