# **Numpy**
---

In [1]:
import numpy as np
type(np.random)

module

In [2]:
rolls = np.random.randint(low=1, high=6, size=10)
print(rolls)
print(type(rolls))  


[1 2 2 5 3 1 5 5 2 1]
<class 'numpy.ndarray'>


np.random.randint: 균등 분포 정수 난수 1개 생성  

# **ndarray**
---
Numpy의 핵심인 다차원 행렬 자료구조 클래스
선언은 a = np.array([])의 형태    
출력형태는 List와 같음  

### **Python list**
* 여러가지 타입의 원소 
* Linked list 구현  
* 메모리 용량이 크고 속도가 느림  
* 벡터화 연산 불가  

### **Numpy ndarray** 
* 동일 타입의 원소  
* contiguous memory layout (연속 메모리 할당) : C계열 메모리
* 메모리 최적화, 계산 속도 향상  
* 벡터화 연산 가능  

In [3]:
# [1,2,3] + 10 이라는 연산은 말도 안된다 but 벡터화 연산에서는 ?
print(rolls)
print(rolls+10)

[1 2 2 5 3 1 5 5 2 1]
[11 12 12 15 13 11 15 15 12 11]


In [4]:
xlist = [[1,2,3],[4,5,6]]
print(xlist)
copyxList = np.asarray(xlist)
copyxList

[[1, 2, 3], [4, 5, 6]]


array([[1, 2, 3],
       [4, 5, 6]])

np.asarray()와 np.array()는 기능에 있어서 차이는 없지만 복사 관련하여 차이가 있음  
(정확히는 모르겠음..)

In [5]:
#ndarray 출력하기
print(copyxList[0,2]) 
print(copyxList[0])

3
[1 2 3]


# **Tensorflow**
---

In [6]:
import tensorflow as tf
a = tf.constant(1)
b = tf.constant(1)
a + b



<tf.Tensor: shape=(), dtype=int32, numpy=2>